apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: ToolServer
metadata:
  name: customer-database
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "showcase-insurance-claims.labels" . | nindent 4 }}
spec:
  protocol: mcp
  transportType: http
  image: {{ .Values.images.customerDatabase.repository }}:{{ .Values.images.customerDatabase.tag }}
  port: 8000
  env:
    - name: OTEL_SERVICE_NAME
      value: customer-database
  {{- with .Values.extraEnv }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: ToolRoute
metadata:
  name: customer-database
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "showcase-insurance-claims.labels" . | nindent 4 }}
spec:
  {{- with .Values.toolGateway.ref }}
  toolGatewayRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  upstream:
    toolServerRef:
      name: customer-database
