#
# Composite Action: Docker Build
#
# This composite action builds a Docker image and outputs the image tag for use in subsequent steps.
#
name: Docker Build
description: 'Build a Docker image and output image details'

inputs:
  image_name:
    description: 'Name of the image to build'
    required: true
    type: string
  dockerfile:
    description: 'Path to the Dockerfile'
    required: true
    type: string
  build_arg_key:
    description: 'Build argument key name (optional - omit for images without build args)'
    required: false
    type: string
    default: ''
  image_tag:
    description: 'Image tag to use'
    required: false
    type: string
    default: latest
  docker_context:
    description: 'Path to the Docker build context'
    required: false
    type: string
    default: '.'

outputs:
  image-name:
    description: 'Full image name with registry and tag'
    value: 'europe-west3-docker.pkg.dev/qaware-paal/agentic-layer-private/${{ inputs.image_name }}:${{ inputs.image_tag }}'

runs:
  using: composite
  steps:
    - name: 'Build Docker Image (with build args)'
      if: ${{ inputs.build_arg_key != '' }}
      uses: 'docker/build-push-action@v6'
      with:
        context: ${{ inputs.docker_context }}
        file: ${{ inputs.dockerfile }}
        push: false
        load: true   # Load image into local Docker daemon for potential pushing
        tags: europe-west3-docker.pkg.dev/qaware-paal/agentic-layer-private/${{ inputs.image_name }}:${{ inputs.image_tag }}
        build-args: |
          ${{ inputs.build_arg_key }}=${{ inputs.image_name }}

    - name: 'Build Docker Image (without build args)'
      if: ${{ inputs.build_arg_key == '' }}
      uses: 'docker/build-push-action@v6'
      with:
        context: ${{ inputs.docker_context }}
        file: ${{ inputs.dockerfile }}
        push: false
        load: true   # Load image into local Docker daemon for potential pushing
        tags: europe-west3-docker.pkg.dev/qaware-paal/agentic-layer-private/${{ inputs.image_name }}:${{ inputs.image_tag }}